---
- name: "Install using the right OS"
  include_tasks: "{{ ansible_facts['os_family'] }}.yaml"
  tags:
    - always

- name: "Copy out pritunl-client-parser"
  copy:
    src: files/pritunl-client-parser.py
    dest: ~/pritunl-client-parser.py

- name: "Run the python script, and get list"
  shell: "pritunl-client list | python3 ~/pritunl-client-parser.py"
  register: pritunl_list

- name: "Run the python script, and get url"
  ansible.builtin.script:
    cmd: "files/get-config-url.py -url {{ pritunl_server_url }} -token {{ pritunl_server_api_token }} -secret {{ pritunl_server_api_secret }} -organization {{ pritunl_organization }}"
  register: pritunl_url
  args:
    executable: python3
  when: pritunl_list.stdout|from_json|list|selectattr("name", "equalto", ansible_nodename)|list|length == 0

- name: "Enrole pritunl-client profile"
  shell: "pritunl-client add {{ pritunl_url.stdout_lines[0] }}"
  when: pritunl_list.stdout|from_json|list|selectattr("name", "equalto", ansible_nodename)|list|length == 0
  register: add_profile

# TODO: Fix conditionnal so this doesn't need to run all the time
- name: "Run the python script, and get list"
  shell: "pritunl-client list | python3 ~/pritunl-client-parser.py"
  register: pritunl_list2
  #when: add_profile.changed

- name: "Start pritunl-client profile"
  shell: 'pritunl-client start {{ (pritunl_list2.stdout|from_json|list|selectattr("name", "equalto", ansible_nodename)|list)[0].id }} --mode wg'
  when: (pritunl_list2.stdout|from_json|list|selectattr("name", "equalto", ansible_nodename)|list|first).status == "Disconnected"