- name: Copy out the pritunl repo file
  template:
    src: "pritunl-RedHat.j2"
    dest: /etc/yum.repos.d/pritunl-RedHat.repo

- name: Check if gpg key is imported
  shell: "gpg --list-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A"
  changed_when: false
  register: gpg_check

- name: Import gpg key
  shell: "{{ item }}"
  with_items:
    - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    - gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
  when: gpg_check.rc == 2

- name: Installing chrony
  dnf: 
   name: "chrony"
   state: latest
   
- name: Installing wget
  dnf: 
   name: "wget"
   state: latest
   
- name: Start service chrony, if not started
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Check if pritunl.rpm is installed
  command: rpm -q {{ pritunl_client_rpm | replace(".rpm", "")}}
  register: rpm_check
  failed_when: rpm_check.rc > 1
  changed_when: false
  when: pritunl_client_rpm is defined

- name: Download & install pritunl-client rpm
  shell: "{{ item }}"
  with_items:
    - wget https://repo.pritunl.com/stable/yum/oraclelinux/8/{{ pritunl_client_rpm }}
    - rpm -U --replacefiles {{ pritunl_client_rpm }}
  when: rpm_check.rc == 1

- name: Install pritunl-client
  yum:
   name: "pritunl-client"
   state: latest
  when: pritunl_client_rpm is undefined