- name: "Install using the right OS"
  include_tasks: "{{ ansible_facts['os_family'] }}.yaml"
  tags:
    - always

- name: "Configure Pritunl"
  include_tasks: "config.yaml"

- name: install plugins
  include_tasks: plugins.yaml
  when: pritunl_plugins is defined
  tags: pritunl-plugins

- name: install patch
  yum:
   name: "patch"
   state: latest

- name: Apply patch to app.py
  ansible.posix.patch:
    src: files/app.py.patch
    dest: /usr/lib/pritunl/lib/python3.6/site-packages/pritunl/app.py

- name: Apply patch to instance.py
  ansible.posix.patch:
    src: files/instance.py.patch
    dest: /usr/lib/pritunl/lib/python3.6/site-packages/pritunl/server/instance.py 

- name: Start service Pritunl, if not started
  ansible.builtin.service:
    name: pritunl
    state: started
    enabled: yes