---
- name: Enable EPEL Repository on REHL 8
  dnf:
    name: ["epel-release", "elrepo-release"]
    state: latest
  become: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: Enable EPEL Repository on REHL 7
  yum:
    name: ["epel-release", "elrepo-release"]
    state: latest
  become: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Copy out the pritunl repo file
  template:
    src: "pritunl-RedHat.j2"
    dest: /etc/yum.repos.d/pritunl-RedHat.repo

- name: Check if gpg key is imported
  shell: "gpg --list-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A"
  changed_when: false
  register: gpg_check
  failed_when: gpg_check.rc > 2 or gpg_check.rc == 1

- name: Import gpg key
  shell: "{{ item }}"
  with_items:
    - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    - gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
  when: gpg_check.rc == 2

- name: Installing chrony
  dnf: 
   name: "chrony"
   state: latest

- name: Installing wget
  dnf: 
   name: "wget"
   state: latest
   
- name: Start service chrony, if not started
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Installing wireguard
  dnf:
   name: ['kmod-wireguard', 'wireguard-tools']
   state: latest
  notify: reboot host


- name: Check if pritunl.rpm is installed
  command: rpm -q {{ pritunl_server_rpm | replace(".rpm", "")}}
  register: rpm_check
  failed_when: rpm_check.rc > 1
  changed_when: false
  when: pritunl_server_rpm is defined

- name: Install pritunl rpm requirements
  dnf:
   name: ['iptables', 'net-tools', 'openvpn', 'pritunl-ndppd', 'python3']
   state: latest
  when: rpm_check.rc == 1

- name: Download & install pritunl rpm
  shell: "{{ item }}"
  with_items:
    - wget https://repo.pritunl.com/stable/yum/oraclelinux/8/{{ pritunl_server_rpm }}
    - rpm -U --replacefiles {{ pritunl_server_rpm }}
  when: rpm_check.rc == 1
  notify: restart pritunl

- name: Install pritunl
  yum:
   name: "pritunl"
   state: latest
  when: pritunl_server_rpm is undefined

- name: Replacing openvpn for pritunl-openvpn
  dnf:
   name: "pritunl-openvpn"
   state: latest
   allowerasing: yes

- name: "Increase open file limits"
  block:
  - name: Increase open file limit
    pam_limits:
      domain: "*"
      limit_type: hard
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: "*"
      limit_type: soft
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: root
      limit_type: hard
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: root
      limit_type: soft
      limit_item: nofile
      value: 64000
  when: pritunl_increase_open_limit_file

- name: Set CAP_NET_BIND_SERVICE=+eip on /usr/bin/openvpn
  community.general.capabilities:
    path: /usr/bin/openvpn
    capability: CAP_NET_BIND_SERVICE+eip
    state: present

# - name: Set CAP_NET_BIND_SERVICE=+eip on /usr/bin/pritunl/bin/python2
#   community.general.capabilities:
#     path: /usr/bin/pritunl/bin/python2
#     capability: CAP_NET_BIND_SERVICE+eip
#     state: present

# - name: Set CAP_NET_BIND_SERVICE=+eip on /usr/bin/pritunl
#   community.general.capabilities:
#     path: /usr/bin/pritunl
#     capability: CAP_NET_BIND_SERVICE+eip
#     state: present

- name: Check to see if semodule is loaded
  shell: "semodule -l | grep -i 'pritunl-openvpn'"
  register: grep_output
  failed_when: "grep_output.rc == 2"
  changed_when: false
  ignore_errors: true

- name: Installing setools
  dnf:
   name: "setools"
   state: latest
  when: grep_output.stdout == ""

- name: Copy out the pritunl openvpn selinux policy file
  copy:
    src: files/pritunl-openvpn.cil
    dest: ~/pritunl-openvpn.cil
  when: grep_output.stdout == ""

- name: Compile SELinux policy
  command: checkmodule -M -m -o ~/pritunl-openvpn.mod ~/pritunl-openvpn.cil
  when: grep_output.stdout == ""

- name: Package SELinux policy
  command: semodule_package -o ~/pritunl-openvpn.pp -m ~/pritunl-openvpn.mod
  when: grep_output.stdout == ""

- name: Load SELinux policy package
  command: semodule -i ~/pritunl-openvpn.pp
  when: grep_output.stdout == ""
  
- name: Remove temporary policy files
  ansible.builtin.file:
    path: ~/pritunl-openvpn.*
    state: absent
  when: grep_output.stdout == ""

- name: "Configure ufw"
  include_tasks: "ufw.yaml"