---
- name: Installing ufw
  yum:
   name: "ufw"
   state: latest

- name: Start service ufw, if not started
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes

- name: Allow all access to udp port 443 (OpenVPN)
  community.general.ufw:
    rule: allow
    port: '443'
    proto: udp

- name: Allow all access to TCP port 443 (WebUI)
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow all access to udp port 51820 (Wireguard)
  community.general.ufw:
    rule: allow
    port: '51820'
    proto: udp

- name: "Limit SSH port"
  community.general.ufw:
    rule: limit
    name: SSH

# sudo ufw default deny incoming
- name: Firewall default to deny incomming
  community.general.ufw:
    default: deny
    direction: incoming
    
# sudo ufw default allow outgoing
- name: Firewall default to allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing